hpi-swt2/bookkeeper-portal-red

- app/models/group.rb
- app/models/item.rb
- app/models/lending.rb
- app/models/membership.rb
- app/models/reservation.rb
- app/models/user.rb
- db/migrate/20221121205846_create_base_datamodel.rb
- db/schema.rb
- spec/factories/groups.rb
- spec/factories/items.rb
- spec/factories/lendings.rb
- spec/factories/memberships.rb
- spec/factories/reservations.rb
- spec/models/group_spec.rb
- spec/models/lending_spec.rb
- spec/models/membership_spec.rb
- spec/models/reservation_spec.rb
> Add basic models

- app/controllers/application_controller.rb
- app/views/layouts/_navbar.html.erb
- config/routes.rb
Fix routing, so that tests are green.
> Gdm scope language fix

- .github/workflows/ci_cd.yml
- app/controllers/items_controller.rb
- app/models/user.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20221127115524_disallow_null_for_dates.rb
- spec/features/items/edit_spec.rb
- spec/features/items/new_spec.rb
- spec/features/items/show_spec.rb
Our Leitfaden mentions that Rubocop needs to pass before a PR can be merged. This PR enforces this by adding a check to CI.
> feat: run rubocop as part of CI

- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/profiles/show.html.erb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- config/locales/views/landing_page/de.yml
> feat: multi-language support for login page

- app/models/group.rb
- app/models/item.rb
- app/models/permission.rb
- app/models/user.rb
- spec/models/group_spec.rb
- spec/models/item_spec.rb
> refactor: rename can_lend permission to can_borrow

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.erb
- config/routes.rb
> feat: language icon in nav bar

- app/controllers/items_controller.rb
- app/views/items/_item.json.jbuilder
- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
- db/migrate/20221207125838_add_lat_lng_to_items.rb
- db/schema.rb
> Add item location tracking and map

- app/assets/stylesheets/application.scss
> Adapt Bootstrap to match style guide

- app/models/user.rb
- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
> Rename `lending_rights?` to `can_borrow?`

- app/controllers/items_controller.rb
- app/views/items/show.html.erb
> fix: redirect and duplicated messages on item show page

- app/models/concerns/export_pdf.rb
> Rename qrcode parameter

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/_book_form.html.erb
- app/views/items/_game_form.html.erb
- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/_item_type_form.html.erb
- app/views/items/_movie_form.html.erb
- app/views/items/_other_form.html.erb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
- app/views/landing_page/index.html.erb
- app/views/layouts/_item_grid.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- db/schema.rb
- spec/factories/items.rb
- spec/features/items/edit_spec.rb
- spec/features/items/show_spec.rb
- spec/requests/items_spec.rb
- spec/views/items/edit.html.erb_spec.rb
- spec/views/items/index.html.erb_spec.rb
- spec/views/items/show.html.erb_spec.rb
- spec/views/landing_page/landing_page_spec.rb
Resolves #94, resolves #159, resolves #160, resolves #169
Resolves multiple issues at once, because they all relied on #94 and I didn't want to wait for the review.
> Create / Edit / View Item pages depending on item type

- app/views/items/_form.html.erb
- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- app/views/layouts/_item_grid.html.erb
> feat: Make all simple links to nicely looking buttons

- app/controllers/items_controller.rb
- app/mailers/notification_mailer.rb
> fix: use uniform time datatypes

- app/views/items/_item_smallscreen.html.erb
> Change borrow button color in mobile view

- app/views/items/_item_smallscreen.html.erb
> Fix overlying map in small show item view

- app/views/items/_book_form.html.erb
- db/migrate/20221202151158_add_item_types.rb
- db/migrate/20230108133416_change_isbn_to_string.rb
- db/schema.rb
- spec/factories/items.rb
Closes #217. Continuation of the work in #218.
> Change ISBN column type to `string`

- app/controllers/analytics_controller.rb
- app/views/analytics/show.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- config/routes.rb
Adds a skeleton page at /analytics
> Added analytics page

- app/views/layouts/_navbar.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- spec/features/items/reservation_spec.rb
> feat: link to borrowed assets in navbar

- app/views/items/show.html.erb
- app/views/qr_reader/scan.html.erb
This fixes #135 and thereby fixes #183.
> Correctly loading item map and QR code scanner

- app/views/items/_search_form.html.erb
- app/views/layouts/_navbar.html.erb
> fix: keep locale url parameter

- app/views/notification_mailer/send_reminder.html.erb
- lib/tasks/overdue_reminder.rake
- lib/tasks/return_reminder.rake
- lib/tasks/weekly_overdue_reminder.rake
- spec/features/notifications/auto_notification_spec.rb
- Changed Mail layout
- Added quotes around item name
- Added test for fixed issue
> fix: Fixed Weekly notification on due date

- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
> improve item detail page

- app/views/groups/index.html.erb
- config/locales/views/groups/de.yml
- config/locales/views/groups/en.yml
> feat: add notice in my groups page if group has no items

- app/views/groups/index.html.erb
> feat: remove grey backgrounds on group index view

- app/models/item.rb
- app/views/items/_game_form.html.erb
- app/views/items/_item_type_form.html.erb
- app/views/items/edit.html.erb
- app/views/items/show.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- db/migrate/20230123084800_game_properties_to_string.rb
- db/schema.rb
- spec/factories/items.rb
> Game Properties as Text

- app/views/groups/index.html.erb
> fix: close div in groups index page correctly

- app/views/qr_reader/scan.html.erb
> fix: Fix the QR-Code scanner code to select the correct camera

- app/controllers/items_controller.rb
> fix: filter and sort on every grid view

- app/views/items/_item_card.html.erb
- app/views/items/_owner_component.html.erb
- spec/views/items/index.html.erb_spec.rb
- spec/views/landing_page/landing_page_spec.rb
> feat: changed grid view card ui

- app/components/item_borrow_button.rb
- app/components/item_borrow_button_big.html.erb
- app/components/item_borrow_button_big.rb
- app/components/item_borrow_button_small.html.erb
- app/components/item_borrow_button_small.rb
- app/controllers/items_controller.rb
- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/show.html.erb
Fixes bug, where location is not saved on smallscreen
> fix: separate buttons for large/small, location is now saved correctly

- app/views/qr_reader/scan.html.erb
> fix: Fix the QR-Code scanner code to close the camera when leaving the page

- app/views/layouts/_navbar.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- spec/features/users/oidc_login_spec.rb
> feat: allow logging out via navbar button

- app/views/qr_reader/scan.html.erb
This (hopefully) fixes the issue of the camera not loading after a QR code is scanned.
> fix: Correctly load and close QR code scanner

- app/helpers/application_helper.rb
An incredibly important issue implemented with blessing from our PO, Chief of Product Specification and Lead Visionary, Raban.
> fix: Changed language selection flag from US to GB

- app/views/items/_item_largescreen.html.erb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/_item_type_form.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
> feat: tooltips

- app/models/item.rb
- app/views/items/_item_smallscreen.html.erb
- app/views/items/show.html.erb
- app/views/layouts/_item_history_table.html.erb
- config/locales/views/landing_page/de.yml
- config/locales/views/landing_page/en.yml
- spec/features/items/show_spec.rb
- spec/models/item_spec.rb
Show history of all lendings of an item on its page.
Resolves #230
> item lending history

- app/views/layouts/_notification_inbox.html.erb
> fix: notification hint not showing up

- app/views/qr_reader/scan.html.erb
> fix: fit video to page width

- app/views/items/_item_card.html.erb
- app/views/items/_item_largescreen.html.erb
- app/views/items/_items_images_component.html.erb
> fix: broken image alignment on mobile in grid view

- app/controllers/analytics_controller.rb
- app/views/analytics/_item_history_table.html.erb
- spec/features/analytics/lending_history_spec.rb
Fixes history table filter dropdown contains only unique items. Also the tables were switched and not corresponding to their mode (borrowed from me or borrowed by me)
> fix: history table
